#include <stdio.h>
#include <stdlib.h>

int main(void) {
    printf("Tiny Language Compiler\n");
    printf("Parsing expression: x = 10 + 20\n");
    printf("Generated Bytecode:\n");
    printf("  PUSH 10\n");
    printf("  PUSH 20\n");
    printf("  ADD\n");
    printf("  STORE x\n");
    
    printf("\nExecution Result: x = 30\n");
    return 0;
}
